<?php

namespace Test\AbraFlexi;

use AbraFlexi\Formats;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-10-02 at 10:07:20.
 */
class FormatsTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Formats
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Formats();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers AbraFlexi\Formats::byContentType
     * @todo   Implement testbyContentType().
     */
    public function testbyContentType() {
        $this->assertEquals('', $this->object->byContentType());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Formats::bySuffix
     * @todo   Implement testbySuffix().
     */
    public function testbySuffix() {
        $this->assertEquals('', $this->object->bySuffix());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Formats::suffixToContentType
     * @todo   Implement testsuffixToContentType().
     */
    public function testsuffixToContentType() {
        $this->assertEquals('', $this->object->suffixToContentType());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Formats::contentTypeToSuffix
     * @todo   Implement testcontentTypeToSuffix().
     */
    public function testcontentTypeToSuffix() {
        $this->assertEquals('', $this->object->contentTypeToSuffix());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
