<?php

namespace Test\AbraFlexi;

use AbraFlexi\InterniDoklad;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-10-02 at 10:07:15.
 */
class InterniDokladTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var InterniDoklad
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new InterniDoklad();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers AbraFlexi\InterniDoklad::getLabels
     * @todo   Implement testgetLabels().
     */
    public function testgetLabels() {
        $this->assertEquals('', $this->object->getLabels());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\InterniDoklad::setLabel
     * @todo   Implement testsetLabel().
     */
    public function testsetLabel() {
        $this->assertEquals('', $this->object->setLabel());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\InterniDoklad::unsetLabel
     * @todo   Implement testunsetLabel().
     */
    public function testunsetLabel() {
        $this->assertEquals('', $this->object->unsetLabel());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\InterniDoklad::unsetLabels
     * @todo   Implement testunsetLabels().
     */
    public function testunsetLabels() {
        $this->assertEquals('', $this->object->unsetLabels());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\InterniDoklad::getFirmaObject
     * @todo   Implement testgetFirmaObject().
     */
    public function testgetFirmaObject() {
        $this->assertEquals('', $this->object->getFirmaObject());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\InterniDoklad::getSumFromAbraFlexi
     * @todo   Implement testgetSumFromAbraFlexi().
     */
    public function testgetSumFromAbraFlexi() {
        $this->assertEquals('', $this->object->getSumFromAbraFlexi());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\InterniDoklad::getSubItems
     * @todo   Implement testgetSubItems().
     */
    public function testgetSubItems() {
        $this->assertEquals('', $this->object->getSubItems());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\InterniDoklad::setSubitems
     * @todo   Implement testsetSubitems().
     */
    public function testsetSubitems() {
        $this->assertEquals('', $this->object->setSubitems());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\InterniDoklad::getSubMenuName
     * @todo   Implement testgetSubMenuName().
     */
    public function testgetSubMenuName() {
        $this->assertEquals('', $this->object->getSubMenuName());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\InterniDoklad::getSubObjects
     * @todo   Implement testgetSubObjects().
     */
    public function testgetSubObjects() {
        $this->assertEquals('', $this->object->getSubObjects());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\InterniDoklad::getEmail
     * @todo   Implement testgetEmail().
     */
    public function testgetEmail() {
        $this->assertEquals('', $this->object->getEmail());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\InterniDoklad::getRecipients
     * @todo   Implement testgetRecipients().
     */
    public function testgetRecipients() {
        $this->assertEquals('', $this->object->getRecipients());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\InterniDoklad::docTypeToPurpose
     * @todo   Implement testdocTypeToPurpose().
     */
    public function testdocTypeToPurpose() {
        $this->assertEquals('', $this->object->docTypeToPurpose());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\InterniDoklad::getChanges
     * @todo   Implement testgetChanges().
     */
    public function testgetChanges() {
        $this->assertEquals('', $this->object->getChanges());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
