<?php

namespace Test\AbraFlexi;

use AbraFlexi\Priloha;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-10-02 at 10:07:31.
 */
class PrilohaTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Priloha
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Priloha();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers AbraFlexi\Priloha::attachFile
     * @todo   Implement testattachFile().
     */
    public function testattachFile() {
        $this->assertEquals('', $this->object->attachFile());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Priloha::getDownloadUrl
     * @todo   Implement testgetDownloadUrl().
     */
    public function testgetDownloadUrl() {
        $this->assertEquals('', $this->object->getDownloadUrl());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Priloha::getFirstAttachment
     * @todo   Implement testgetFirstAttachment().
     */
    public function testgetFirstAttachment() {
        $this->assertEquals('', $this->object->getFirstAttachment());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Priloha::getAttachment
     * @todo   Implement testgetAttachment().
     */
    public function testgetAttachment() {
        $this->assertEquals('', $this->object->getAttachment());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Priloha::download
     * @todo   Implement testdownload().
     */
    public function testdownload() {
        $this->assertEquals('', $this->object->download());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Priloha::saveToFile
     * @todo   Implement testsaveToFile().
     */
    public function testsaveToFile() {
        $this->assertEquals('', $this->object->saveToFile());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Priloha::addAttachmentFromFile
     * @todo   Implement testaddAttachmentFromFile().
     */
    public function testaddAttachmentFromFile() {
        $this->assertEquals('', $this->object->addAttachmentFromFile());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Priloha::addAttachment
     * @todo   Implement testaddAttachment().
     */
    public function testaddAttachment() {
        $this->assertEquals('', $this->object->addAttachment());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Priloha::getAttachmentsList
     * @todo   Implement testgetAttachmentsList().
     */
    public function testgetAttachmentsList() {
        $this->assertEquals('', $this->object->getAttachmentsList());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
