<?php

declare(strict_types=1);

/**
 * This file is part of the EaseCore package.
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi;

use AbraFlexi\Root;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-10-02 at 10:07:17.
 */
class RootTest extends \PHPUnit\Framework\TestCase
{
    protected Root $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Root();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\Root::uploadCertificate
     *
     * @todo   Implement testuploadCertificate().
     */
    public function testuploadCertificate(): void
    {
        $this->assertEquals('', $this->object->uploadCertificate());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\Root::companies
     *
     * @todo   Implement testcompanies().
     */
    public function testcompanies(): void
    {
        $this->assertEquals('', $this->object->companies());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
