<?php

namespace Test\AbraFlexi;

use AbraFlexi\UcetniObdobi;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-10-02 at 10:07:09.
 */
class UcetniObdobiTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var UcetniObdobi
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new UcetniObdobi();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }
}
