<?php

namespace Test\AbraFlexi;

use AbraFlexi\Zurnal;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-10-02 at 10:07:37.
 */
class ZurnalTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Zurnal
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Zurnal();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers AbraFlexi\Zurnal::getAllChanges
     * @todo   Implement testgetAllChanges().
     */
    public function testgetAllChanges() {
        $this->assertEquals('', $this->object->getAllChanges());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Zurnal::getLastChange
     * @todo   Implement testgetLastChange().
     */
    public function testgetLastChange() {
        $this->assertEquals('', $this->object->getLastChange());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
