<?php

namespace Test\AbraFlexi;

use AbraFlexi\Changes;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-02-13 at 17:44:33.
 */
class ChangesTest extends ROTest
{

    /**
     * @var Changes
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Changes();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers AbraFlexi\Changes::enable
     * @todo   Implement testenable().
     */
    public function testenable()
    {
        $this->assertEquals('', $this->object->enable());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Changes::disable
     * @todo   Implement testdisable().
     */
    public function testdisable()
    {
        $this->assertEquals('', $this->object->disable());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Changes::getStatus
     * @todo   Implement testgetStatus().
     */
    public function testgetStatus()
    {
        $this->assertEquals('', $this->object->getStatus());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Changes::recordExists
     * @todo   Implement testrecordExists().
     */
    public function testrecordExists()
    {
        $this->assertEquals('', $this->object->recordExists());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Changes::getGlobalVersion
     * @todo   Implement testgetGlobalVersion().
     */
    public function testgetGlobalVersion()
    {
        $this->assertEquals('', $this->object->getGlobalVersion());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Changes::rawXmlToArray
     * @todo   Implement testrawXmlToArray().
     */
    public function testrawXmlToArray()
    {
        $this->assertEquals('', $this->object->rawXmlToArray());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Changes::getVazby
     * @todo   Implement testgetVazby().
     */
    public function testgetVazby()
    {
        $this->assertEquals('', $this->object->getVazby());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
