<?php

namespace Test\AbraFlexi;

use AbraFlexi\DateTime;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-10-19 at 15:21:39.
 */
class DateTimeTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var DateTime
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new DateTime();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * Test Constructor
     *
     * @covers AbraFlexi\DateTime::__construct
     */
    public function testConstructor() {
        $classname = get_class($this->object);

        // Get mock, without the constructor being called
        $mock = $this->getMockBuilder($classname)
                ->disableOriginalConstructor()
                ->getMockForAbstractClass();

        $mock->__construct('');
        $this->assertTrue($mock->isNull);

        $mock->__construct('NOW');
        $this->assertFalse($mock->isNull);
        $mock->__construct('2021-11-09T12:03:53++00:00');

        $mock->__construct('2021-10-19T15:12:53.435+02:00');
    }

    /**
     * @covers AbraFlexi\DateTime::__toString
     */
    public function test__toString() {
        $this->object->setDate(2323, 2, 3)->setTime(2, 3, 2, 3);
        $this->assertEquals('2323-02-03T02:03:02.000003++00:00', $this->object->__toString());
    }

}
