<?php

namespace Test\AbraFlexi;

use AbraFlexi\Dodavatel;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2023-11-18 at 18:14:35.
 */
class DodavatelTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Dodavatel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Dodavatel();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers AbraFlexi\Dodavatel::getLabels
     * @todo   Implement testgetLabels().
     */
    public function testgetLabels() {
        $this->assertEquals('', $this->object->getLabels());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Dodavatel::setLabel
     * @todo   Implement testsetLabel().
     */
    public function testsetLabel() {
        $this->assertEquals('', $this->object->setLabel());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Dodavatel::unsetLabel
     * @todo   Implement testunsetLabel().
     */
    public function testunsetLabel() {
        $this->assertEquals('', $this->object->unsetLabel());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Dodavatel::unsetLabels
     * @todo   Implement testunsetLabels().
     */
    public function testunsetLabels() {
        $this->assertEquals('', $this->object->unsetLabels());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers AbraFlexi\Dodavatel::getFirmaObject
     * @todo   Implement testgetFirmaObject().
     */
    public function testgetFirmaObject() {
        $this->assertEquals('', $this->object->getFirmaObject());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
