<?php
/**
 * FlexiBee - Objekt adresáře.
 *
 * @author     Vítězslav Dvořák <vitex@arachne.cz>
 * @copyright  (C) 2015-2017 Spoje.Net
 */

namespace Test\FlexiBee;

use FlexiBee\Adresar;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-27 at 17:54:36.
 */
class AdresarTest extends FlexiBeeRWTest
{
    /**
     * @var Adresar
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Adresar();
    }

    /**
     * @covers FlexiBee\Adresar::getNotificationEmailAddress
     */
    public function testGetNotificationEmailAddress()
    {
        $this->object->getNotificationEmailAddress();
    }

    /**
     * @covers FlexiBee\Adresar::getCellPhoneNumber
     */
    public function testGetCellPhoneNumber()
    {
        $this->object->getCellPhoneNumber();
    }

    /**
     * @covers FlexiBee\Adresar::getAnyPhoneNumber
     */
    public function testGetAnyPhoneNumber()
    {
        $this->object->getAnyPhoneNumber();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }
}
