<?php

namespace Test\FlexiBee;

use FlexiBee\Smlouva;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-10 at 12:31:59.
 */
class SmlouvaTest extends FlexiBeeRWTest
{
    /**
     * @var Smlouva
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Smlouva();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers FlexiBee\Smlouva::generovaniFaktur
     */
    public function testGenerovaniFaktur()
    {
        $this->object->setMyKey(1);
        $this->object->generovaniFaktur();
        $this->object->dataReset();
        $this->object->generovaniFaktur();
    }
}
