<?php

namespace Test\AbraFlexi;

use AbraFlexi\Date;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2021-10-17 at 16:07:28.
 */
class DateTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Date
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Date();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * Test Constructor
     *
     * @covers AbraFlexi\Date::__construct
     */
    public function testConstructor() {
        $classname = get_class($this->object);

        // Get mock, without the constructor being called
        $mock = $this->getMockBuilder($classname)
                ->disableOriginalConstructor()
                ->getMockForAbstractClass();

        $mock->__construct('');
        $this->assertTrue($mock->isNull);

        $mock->__construct('NOW');
        $this->assertFalse($mock->isNull);

        $mock->__construct('2021-10-16');

        $mock->__construct('2021-10-16+02:00');

        $mock->__construct('2021-10-18-02:00');

        $mock->__construct('2021-10-16Z');
    }

    /**
     * @covers AbraFlexi\Date::__toString
     */
    public function test__toString() {
        $this->assertEquals(date('Y-m-d'), $this->object->__toString());
    }

}
