<?php

declare(strict_types=1);

/**
 * This file is part of the EaseCore package.
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi;

use AbraFlexi\DodavatelskaSmlouva;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-10-02 at 10:07:41.
 */
class DodavatelskaSmlouvaTest extends \PHPUnit\Framework\TestCase
{
    protected DodavatelskaSmlouva $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new DodavatelskaSmlouva();
    }

//    /**
//     * Tears down the fixture, for example, closes a network connection.
//     * This method is called after a test is executed.
//     */
//    protected function tearDown(): void
//    {
//    }
//
//    /**
//     * @covers \AbraFlexi\DodavatelskaSmlouva::generateInvoices
//     *
//     * @todo   Implement testgenerateInvoices().
//     */
//    public function testgenerateInvoices(): void
//    {
//        $this->assertEquals('', $this->object->generateInvoices());
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete('This test has not been implemented yet.');
//    }
//
//    /**
//     * @covers \AbraFlexi\DodavatelskaSmlouva::getLabels
//     *
//     * @todo   Implement testgetLabels().
//     */
//    public function testgetLabels(): void
//    {
//        $this->assertEquals('', $this->object->getLabels());
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete('This test has not been implemented yet.');
//    }
//
//    /**
//     * @covers \AbraFlexi\DodavatelskaSmlouva::setLabel
//     *
//     * @todo   Implement testsetLabel().
//     */
//    public function testsetLabel(): void
//    {
//        $this->assertEquals('', $this->object->setLabel());
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete('This test has not been implemented yet.');
//    }
//
//    /**
//     * @covers \AbraFlexi\DodavatelskaSmlouva::unsetLabel
//     *
//     * @todo   Implement testunsetLabel().
//     */
//    public function testunsetLabel(): void
//    {
//        $this->assertEquals('', $this->object->unsetLabel());
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete('This test has not been implemented yet.');
//    }
//
//    /**
//     * @covers \AbraFlexi\DodavatelskaSmlouva::unsetLabels
//     *
//     * @todo   Implement testunsetLabels().
//     */
//    public function testunsetLabels(): void
//    {
//        $this->assertEquals('', $this->object->unsetLabels());
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete('This test has not been implemented yet.');
//    }
//
//    /**
//     * @covers \AbraFlexi\DodavatelskaSmlouva::getSubItems
//     *
//     * @todo   Implement testgetSubItems().
//     */
//    public function testgetSubItems(): void
//    {
//        $this->assertEquals('', $this->object->getSubItems());
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete('This test has not been implemented yet.');
//    }
//
//    /**
//     * @covers \AbraFlexi\DodavatelskaSmlouva::setSubitems
//     *
//     * @todo   Implement testsetSubitems().
//     */
//    public function testsetSubitems(): void
//    {
//        $this->assertEquals('', $this->object->setSubitems());
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete('This test has not been implemented yet.');
//    }
//
//    /**
//     * @covers \AbraFlexi\DodavatelskaSmlouva::getSubMenuName
//     *
//     * @todo   Implement testgetSubMenuName().
//     */
//    public function testgetSubMenuName(): void
//    {
//        $this->assertEquals('', $this->object->getSubMenuName());
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete('This test has not been implemented yet.');
//    }
//
//    /**
//     * @covers \AbraFlexi\DodavatelskaSmlouva::getSubObjects
//     *
//     * @todo   Implement testgetSubObjects().
//     */
//    public function testgetSubObjects(): void
//    {
//        $this->assertEquals('', $this->object->getSubObjects());
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete('This test has not been implemented yet.');
//    }
//
//    /**
//     * @covers \AbraFlexi\DodavatelskaSmlouva::getFirmaObject
//     *
//     * @todo   Implement testgetFirmaObject().
//     */
//    public function testgetFirmaObject(): void
//    {
//        $this->assertEquals('', $this->object->getFirmaObject());
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete('This test has not been implemented yet.');
//    }
}
