<?php

declare(strict_types=1);

/**
 * This file is part of the SpojeNet\AbraFlexi package.
 *
 * (c) 2019-2024 SpojeNet s.r.o. <http://spoje.net/>
 * (c) 2025 SpojeNetIT s.r.o. <http://spojenet.cz/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi;

use AbraFlexi\Dodavatel;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-10-02 at 10:07:29.
 */
class DodavatelTest extends \PHPUnit\Framework\TestCase
{
    protected Dodavatel $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Dodavatel();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\Dodavatel
     */
    public function testEvidence(): void
    {
        $this->assertEquals('dodavatel', $this->object->evidence);
    }
}