<?php

declare(strict_types=1);

/**
 * This file is part of the SpojeNet\AbraFlexi package.
 *
 * (c) 2019-2024 SpojeNet s.r.o. <http://spoje.net/>
 * (c) 2025 SpojeNetIT s.r.o. <http://spojenet.cz/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi;

use AbraFlexi\EvidenceList;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-10-02 at 10:07:00.
 */
class EvidenceListTest extends \PHPUnit\Framework\TestCase
{
    protected EvidenceList $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new EvidenceList();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \AbraFlexi\EvidenceList::getRecordID
     *
     * @todo   Implement testgetRecordID().
     */
    public function testgetRecordID(): void
    {
        $this->assertEquals('', $this->object->getRecordID());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers \AbraFlexi\EvidenceList::getRecordCode
     *
     * @todo   Implement testgetRecordCode().
     */
    public function testgetRecordCode(): void
    {
        $this->assertEquals('', $this->object->getRecordCode());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
