<?php

declare(strict_types=1);

/**
 * This file is part of the EaseCore package.
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi;

use AbraFlexi\Exception;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-10-02 at 10:07:41.
 */
class ExceptionTest extends \PHPUnit\Framework\TestCase
{
    protected Exception $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Exception();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

//    /**
//     * @covers \AbraFlexi\Exception::getErrorMessage
//     *
//     * @todo   Implement testgetErrorMessage().
//     */
//    public function testgetErrorMessage(): void
//    {
//        $this->assertEquals('', $this->object->getErrorMessage());
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete('This test has not been implemented yet.');
//    }
//
//    /**
//     * @covers \AbraFlexi\Exception::getErrorMessages
//     *
//     * @todo   Implement testgetErrorMessages().
//     */
//    public function testgetErrorMessages(): void
//    {
//        $this->assertEquals('', $this->object->getErrorMessages());
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete('This test has not been implemented yet.');
//    }
//
//    /**
//     * @covers \AbraFlexi\Exception::getServerResponse
//     *
//     * @todo   Implement testgetServerResponse().
//     */
//    public function testgetServerResponse(): void
//    {
//        $this->assertEquals('', $this->object->getServerResponse());
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete('This test has not been implemented yet.');
//    }
}
