<?php

declare(strict_types=1);

/**
 * This file is part of the EaseCore package.
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi;

use AbraFlexi\Report;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-10-02 at 10:07:13.
 */
class ReportTest extends \PHPUnit\Framework\TestCase
{
    protected Report $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Report();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

//    /**
//     * @covers \AbraFlexi\Report::loadFromAbraFlexi
//     *
//     * @todo   Implement testloadFromAbraFlexi().
//     */
//    public function testloadFromAbraFlexi(): void
//    {
//        $this->assertEquals('', $this->object->loadFromAbraFlexi());
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete('This test has not been implemented yet.');
//    }
}
