<?php

declare(strict_types=1);

/**
 * This file is part of the EaseCore package.
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\AbraFlexi;

use AbraFlexi\SkladovyPohybPolozka;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2024-10-02 at 10:07:22.
 */
class SkladovyPohybPolozkaTest extends \PHPUnit\Framework\TestCase
{
    protected SkladovyPohybPolozka $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new SkladovyPohybPolozka();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    //    /**
    //     * @covers \AbraFlexi\SkladovyPohybPolozka::addSerialNumber
    //     *
    //     * @todo   Implement testaddSerialNumber().
    //     */
    //    public function testaddSerialNumber(): void
    //    {
    //        $this->assertEquals('', $this->object->addSerialNumber());
    //        // Remove the following lines when you implement this test.
    //        $this->markTestIncomplete('This test has not been implemented yet.');
    //    }
    //
    //    /**
    //     * @covers \AbraFlexi\SkladovyPohybPolozka::getLabels
    //     *
    //     * @todo   Implement testgetLabels().
    //     */
    //    public function testgetLabels(): void
    //    {
    //        $this->assertEquals('', $this->object->getLabels());
    //        // Remove the following lines when you implement this test.
    //        $this->markTestIncomplete('This test has not been implemented yet.');
    //    }
    //
    //    /**
    //     * @covers \AbraFlexi\SkladovyPohybPolozka::setLabel
    //     *
    //     * @todo   Implement testsetLabel().
    //     */
    //    public function testsetLabel(): void
    //    {
    //        $this->assertEquals('', $this->object->setLabel());
    //        // Remove the following lines when you implement this test.
    //        $this->markTestIncomplete('This test has not been implemented yet.');
    //    }
    //
    //    /**
    //     * @covers \AbraFlexi\SkladovyPohybPolozka::unsetLabel
    //     *
    //     * @todo   Implement testunsetLabel().
    //     */
    //    public function testunsetLabel(): void
    //    {
    //        $this->assertEquals('', $this->object->unsetLabel());
    //        // Remove the following lines when you implement this test.
    //        $this->markTestIncomplete('This test has not been implemented yet.');
    //    }
    //
    //    /**
    //     * @covers \AbraFlexi\SkladovyPohybPolozka::unsetLabels
    //     *
    //     * @todo   Implement testunsetLabels().
    //     */
    //    public function testunsetLabels(): void
    //    {
    //        $this->assertEquals('', $this->object->unsetLabels());
    //        // Remove the following lines when you implement this test.
    //        $this->markTestIncomplete('This test has not been implemented yet.');
    //    }
}
