<?php

namespace Test\FlexiPeeHP;

use FlexiPeeHP\Kontakt;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-27 at 18:05:33.
 */
class KontaktTest extends FlexiBeeRWTest
{
    /**
     * @var Kontakt
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Kontakt();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }
}
