<?php

namespace Test\FlexiPeeHP;

use FlexiPeeHP\RadaPokladniPohyb;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-27 at 17:32:10.
 */
class RadaPokladniPohybTest extends FlexiBeeRWTest
{
    /**
     * @var RadaPokladniPohyb
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new RadaPokladniPohyb;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers FlexiPeeHP\RadaPokladniPohyb::getNextRecordCode
     */
    public function testGetNextRecordCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FlexiPeeHP\RadaPokladniPohyb::incrementNextRecordCode
     */
    public function testIncrementNextRecordCode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
