<?php

namespace Test\FlexiPeeHP;

use \FlexiPeeHP\SkladovyPohybPolozka;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-04-24 at 20:29:30.
 */
class SkladovyPohybPolozkaTest extends FlexiBeeRWTest
{
    /**
     * @var SkladovyPohybPolozka
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new SkladovyPohybPolozka();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers FlexiPeeHP\SkladovyPohybPolozka::addSerialNumber
     */
    public function testAddSerialNumber()
    {
        $this->object->addSerialNumber('1');
        $this->object->addSerialNumber('2', true);
        $this->object->addSerialNumber('3');
        $this->assertEquals([
            'mnozMj' => 3,
            'vyrobniCislaPrijata' => [
                ['kod' => '1'],
                ['kod' => '2', 'vyrobnicislohlav' => 1],
                ['kod' => '3']
            ]
            ], $this->object->getData());
    }
}
