<?php

namespace Test\FlexiPeeHP;

use FlexiPeeHP\Strom;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-27 at 17:32:10.
 */
class StromTest extends FlexiBeeRWTest
{
    /**
     * @var Strom
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Strom;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }
}
